version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.8
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      # pull node modules from cache
      - restore_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      # save node modules to cache if they dont exist
      - save_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      # lint source code
      # run unit tests
      # run e2e tests
      # dockerize the project (?)
  deploy:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  # version: 2.1
  build_and_deploy:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "${AWS_ECR_REPO_NAME}"
          region: ${AWS_REGION}
          tag: "${CIRCLE_SHA1}"
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build_and_push_image
      #     aws-region: ${AWS_REGION}
      #     family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #     cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      #     container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
      # - deploy:
      #     requires:
      #       - build
      #   filters:
      #     branches:
      #       only:
      #         - master
