version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.8
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      # pull node modules from cache
      - restore_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      # save node modules to cache if they dont exist
      - save_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      # lint source code
      # run unit tests
      # run e2e tests
      # dockerize the project (?)
workflows:
  build_and_deploy:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          requires:
            - build
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "${AWS_ECR_REPO_NAME}"
          region: ${AWS_REGION}
          tag: "${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}"
          filters:
            branches:
                only:
                  # only run on dev and master branches
                  - dev
                  - master
      # update an ECS service
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          # family: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-task-definition"
          family: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}"
          service-name: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-service"
          # cluster-name: "${AWS_ECR_REPO_NAME}-${CIRCLE_BRANCH}"
          container-image-name-updates: "container=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH},tag=${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}"
          # family: "${AWS_ECR_REPO_NAME}-task-definition"
          # service-name: "${AWS_ECR_REPO_NAME}-service"
          cluster-name: "${AWS_ECR_REPO_NAME}"
          # container-image-name-updates: "container=${AWS_ECR_REPO_NAME},tag=${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}"
          filters:
            branches:
                only:
                  # only run on dev and master branches
                  - dev
                  - master