version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      # pull node modules from cache
      - restore_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      # save node modules to cache if they dont exist
      - save_cache:
          key: testExpress-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      # lint source code
      # run unit tests
      # run e2e tests
      # dockerize the project (?)
  deploy:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #   filters:
      #     branches:
      #       only:
      #         - master
